
services:
    _defaults:
        autowire: true

    ########################################################################
    # FOS Users Standalone Object Service
    Splash\Connectors\FosUser\Objects\User:
        public:     true
        tags:
          # Register Faker Standalone Connector Objects
          - { name: "splash.standalone.object", type : "ThirdParty" }

    ########################################################################
    # FOS Users Events EventSubscriber
    Splash\Connectors\FosUser\EventSubscriber\DoctrineEventsSubscriber:
        arguments:
            - "@splash.connectors.manager"
        tags:
            - 'doctrine.event_subscriber'